# -*- coding: utf-8 -*-
"""exercise_answer (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHnCjuHL7QE1fWm3vL01kuVjG7J6K3uL
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

!pip install word2number

d = pd.read_csv("hiring.csv")
d

d.experience = d.experience.fillna("zero")
d

d.experience = d.experience.apply(w2n.word_to_num)
d

import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score

d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d

reg = linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

reg.predict([[6,8,7]])

reg.predict([[12,10,10]])